version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.15.1
    steps:
      - checkout
      - run:
          name: Install Playwright Dependencies
          command: |
            sudo npx playwright install-deps
      - run:
          name: Rodar Playwright
          command: |
            git clone https://github.com/yxuo/circleci_playwright
            cd circleci_playwright
            npm install
            npx playwright install
            npx playwright test --project=test-project

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
