version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.15.1
    steps:
      - checkout
      - run:
          name: Clone repo externo
          command: git clone https://github.com/yxuo/circleci_playwright
      - run:
          name: Install Yarn
          command: npm install yarn
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Install Playwright
          command: yarn add playwright
      - run:
          name: Run Playwright Tests
          command: yarn playwright test --project=test-project

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
