version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.15.1
    steps:
      - checkout
      - run:
          name: Rodar Playwright
          command: echo "Playwright tests are now run in a separate job after the build step."
            # git clone https://github.com/yxuo/circleci_playwright
            # cd circleci_playwright
            # npm install
            # npx playwright install
            # npx playwright install-deps
            # npx playwright test --project=test-project

# Novo job para rodar Playwright após deploy alpha
  playwright_alpha_test:
    docker:
      - image: cimg/node:20.15.1
    steps:
      - checkout
      - run:
          name: Clonar e instalar dependências
          command: |
            git clone https://github.com/yxuo/circleci_playwright
            cd circleci_playwright
            npm install
            npx playwright install
            npx playwright install-deps
      - run:
          name: Rodar testes Playwright e gerar report
          command: |
            cd circleci_playwright; mkdir output
            npx playwright test --project=test-project > ./output/playwright_output.log; exit_code=$?; echo $exit_code > ./output/playwright_exit_code.txt; exit $exit_code
      - store_artifacts:
          path: circleci_playwright/playwright-report
          destination: playwright-report
      - run:
          name: Google Chat Fail Notification
          when: on_fail
          command: |
            ARTIFACT_URL="https://output.circle-artifacts.com/output/job/${CIRCLE_WORKFLOW_JOB_ID}/artifacts/0/playwright-report/index.html"
            CHAT_INFRA="https://chat.googleapis.com/v1/spaces/AAQAB2H7-7I/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=IVVUiHFtrYOqxXruVdtf3w2KP4DlejBelwgoTJQmIUQ"
            curl --header "Content-Type: application/json" \
            --request POST \
            --data "{\"cards\":[{\"header\":{\"title\":\"Ops! ${CIRCLE_JOB} failed.\",\"subtitle\":\"${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}\",\"imageUrl\":\"https://png.pngtree.com/svg/20170406/icon_failed__1325447.png\",\"imageStyle\":\"IMAGE\"},\"sections\":[{\"widgets\":[{\"keyValue\":{\"topLabel\":\"${CIRCLE_TAG}\",\"content\":\"Credits - ${CIRCLE_USERNAME}\"}}]},{\"widgets\":[{\"buttons\":[{\"textButton\":{\"text\":\"DETAILS\",\"onClick\":{\"openLink\":{\"url\":\"${CIRCLE_BUILD_URL}\"}}}},{\"textButton\":{\"text\":\"REPORT\",\"onClick\":{\"openLink\":{\"url\":\"${ARTIFACT_URL}\"}}}}]}]}]}]}" \
            "$CHAT_INFRA"
      - run:
          name: Google Chat Successful Notification
          when: on_success
          command: |
            ARTIFACT_URL="https://output.circle-artifacts.com/output/job/${CIRCLE_WORKFLOW_JOB_ID}/artifacts/0/playwright-report/index.html"
            CHAT_INFRA="https://chat.googleapis.com/v1/spaces/AAQAB2H7-7I/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=IVVUiHFtrYOqxXruVdtf3w2KP4DlejBelwgoTJQmIUQ"
            curl --header "Content-Type: application/json" \
            --request POST \
            --data "{\"cards\":[{\"header\":{\"title\":\"${CIRCLE_JOB} successful.\",\"subtitle\":\"${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}\",\"imageUrl\":\"https://cdn.dribbble.com/users/314596/screenshots/3241132/media/8e2907a9f80400ee3f40865a3803e6c3.gif\",\"imageStyle\":\"IMAGE\"},\"sections\":[{\"widgets\":[{\"keyValue\":{\"topLabel\":\"${CIRCLE_TAG}\",\"content\":\"Credits - ${CIRCLE_USERNAME}\"}}]},{\"widgets\":[{\"buttons\":[{\"textButton\":{\"text\":\"DETAILS\",\"onClick\":{\"openLink\":{\"url\":\"${CIRCLE_BUILD_URL}\"}}}},{\"textButton\":{\"text\":\"ARTEFATO\",\"onClick\":{\"openLink\":{\"url\":\"${ARTIFACT_URL}\"}}}}]}]}]}]}" \
            "$CHAT_INFRA"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - playwright_alpha_test:
          requires:
            - build

# d